### ISSUE TITLE
No way to use the editor

### ISSUE THREAD

**Issue by Ben-Colwell** [enderslash1010/xc1-save-editor#39]
I downloaded the latest release however there is no application included. I do not see an entry point into how to actually launch this program

**Comment by e-the-real1010** [comment]
The .jar file is the executable for the editor, try to double-click to open it. Make sure you have java runtime environment (jre) installed. 

There is a known issue with .jar files not opening correctly. Try running `java -jar <path to file>.jar` in the command line if opening normally doesn't work

**Comment by Ben-Colwell** [comment]
Thank you for your response :) Jar files were set to auto open using winrar so my JRE didn't pick it up for some reason. Using the CLI I was able to run the application. 

Side note, any intentions or current ability (maybe the flag option?) to enable modifying affinity links? I missed an affinity link near the beginning of the game and would like to have it without restarting the game.

**Comment by e-the-real1010** [comment]
I haven't really looked into affinity links yet, but if you know which specific one u are looking for I can try and look into it
